[package]
name = "service-owner"
version = "0.1.0"
authors = ["kevin <kevin.janada@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.substrate]
categories = [
	"trait",
]

compatibility_version = "2.0.0"


[dependencies]
# Substrate packages
sp-std = { version = '2.0.0', default-features = false }
frame-system = { default-features = false, version = '2.0.1' }


[features]
default = ['std']
std = [
  'sp-std/std',
  'frame-system/std',
]
