[package]
name = "genetic-analyst-services-benchmarking"
version = "2.1.0"
authors = ["agustinustheoo <agustinustheoo@gmail.com>"]
edition = '2021'
description = ''
homepage = ''
license = 'Unlicense'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

# alias "parity-scale-code" to "codec"
[dependencies]
# External Dependencies
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "max-encoded-len"] }

# Substrate packages
## Substrate Primitive Dependencies
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
sp-io = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }

## Substrate Frame Dependencies
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
frame-benchmarking = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }

## Substrate Pallet Dependencies
pallet-assets = { default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.30' }
pallet-balances = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
pallet-timestamp = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
pallet-randomness-collective-flip = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.30', default-features = false }

# Local Dependencies
genetic-analysts = { path = '../../genetic-analysts', default-features = false }
genetic-analyst-services = { path = '../../genetic-analyst-services', default-features = false }
genetic-analyst-qualifications = { path = '../../genetic-analyst-qualifications', default-features = false }
user-profile = { path = '../../user-profile', default-features = false }
genetic-analysis = { path = '../../genetic-analysis', default-features = false }
genetic-analysis-orders = { path = '../../genetic-analysis-orders', default-features = false }
genetic-data = { path = '../../genetic-data', default-features = false }

primitives-duration = { path = '../../../primitives/duration', default-features = false }
primitives-price-and-currency = { path = '../../../primitives/price-and-currency', default-features = false }
primitives-profile-roles = { path = '../../../primitives/profile-roles', default-features = false }
primitives-ethereum-address = { path = '../../../primitives/ethereum-address', default-features = false }

traits-genetic-analyst-services = { path = '../../genetic-analyst-services/traits', default-features = false }
traits-genetic-analyst-qualifications = { path = '../../genetic-analyst-qualifications/traits', default-features = false }

[dev-dependencies]
serde = { default-features = false, version = "1.0.136" }

[features]
default = ['std']
std = [
    'codec/std',

    'sp-io/std',
    'sp-core/std',
    'sp-runtime/std',

    'frame-benchmarking/std',
    'frame-support/std',
    'frame-system/std',

	'pallet-assets/std',
	'pallet-balances/std',
    'pallet-timestamp/std',

	'genetic-data/std',
	'genetic-analysis/std',
    'genetic-analysts/std',
    'genetic-analyst-services/std',
    'genetic-analyst-qualifications/std',
	'genetic-analysis-orders/std',
    'user-profile/std',

    'primitives-duration/std',
    'primitives-price-and-currency/std',
	'primitives-profile-roles/std',
    'primitives-ethereum-address/std',

    'traits-genetic-analyst-services/std',
    'traits-genetic-analyst-qualifications/std',
]
