name: Builder

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

concurrency:
  group: builder-${{ github.ref }}

jobs:
  docker:
    runs-on: ubuntu-20.04
    name: Docker
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: docker/setup-qemu-action@v2
      - name: Set up Buildx
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        id: set-up-buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Initialize Cache Layers
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Generate Metadata
        id: generate-metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=sha,prefix=,enable=${{ startsWith(github.ref, 'refs/heads/') }}
      - name: Build and Push
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.set-up-buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          context: .
          file: .maintain/docker/Dockerfile
          push: true
          tags: ${{ steps.generate-metadata.outputs.tags }}
      - name: Get Short SHA
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        id: get-short-sha
        shell: bash
        run: |
          echo "::set-output name=value::$(git rev-parse --short HEAD)"
      - name: Retag Image and Push
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/${{ github.repository }}:${{ steps.get-short-sha.outputs.value }}
          dst: ${{ steps.generate-metadata.outputs.tags }}
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move Cache
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
